import raw from "@/assets/craft-raw.jpg";
import bgIndigo from "@/assets/clean/bg-indigo.jpg";
import bgLinen from "@/assets/clean/bg-linen.jpg";
import bgStudio from "@/assets/clean/bg-studio.jpg";
import cutout from "@/assets/clean/pot-cutout.png";
import potIndigo from "@/assets/clean/pot-indigo.webp";
import potLinen from "@/assets/clean/pot-linen.webp";
import mask from "@/assets/clean/pot-mask.png";
import potStudio from "@/assets/clean/pot-studio.webp";

export type BgStyle = "studio" | "linen" | "indigo";

export const BG_STYLES: BgStyle[] = ["studio", "linen", "indigo"];

/** Generated by scripts/clean-backgrounds.ts from craft-raw.jpg. */
export const CLEAN = {
  raw,
  cutout,
  mask,
  backgrounds: { studio: bgStudio, linen: bgLinen, indigo: bgIndigo } satisfies Record<
    BgStyle,
    string
  >,
  composites: { studio: potStudio, linen: potLinen, indigo: potIndigo } satisfies Record<
    BgStyle,
    string
  >,
};
